name: "Build and deploy"

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "emortalmc/actions/java/nativeimage@main"
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"

  deploy:
    needs: "build"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "emortalmc/actions/argo-sync@main"
        with:
          deployment-name: "marathon"
          values-path: "server/values/marathon.yaml"
          deployments-repo-token: "${{ secrets.DEPLOYMENTS_REPO_TOKEN }}"
